-- Qualtrics Response — one row per (survey, customer) response.
-- ~80K rows: ~50K NPS responses across 8 quarterly surveys, ~30K CSAT
-- responses (10% post-call rate on Genesys interactions), a few thousand
-- custom outage/DSM/move-in event-triggered responses.
--
-- NPS score 0-10 biased by:
--   archetype (engaged -> promoter, cost_stressed -> detractor)
--   recent outage minutes (depresses NPS)
--   recent complaint (depresses NPS)
--
-- Open-ended comment text generated by ai_query for ~5% of NPS responses
-- (lights up the unstructured-text demo beat). Comment skews to detractor
-- + passive scores; promoters rarely leave comments.

CREATE OR REFRESH MATERIALIZED VIEW raw_qualtrics_response (
  CONSTRAINT non_null_response_id  EXPECT (response_id IS NOT NULL),
  CONSTRAINT non_null_survey_id    EXPECT (survey_id IS NOT NULL),
  CONSTRAINT non_null_customer_id  EXPECT (customer_id IS NOT NULL),
  CONSTRAINT valid_score           EXPECT (score >= 0 AND score <= 10)
)
COMMENT 'Qualtrics survey responses. NPS (quarterly relationship), CSAT (post-call transactional), and custom event-triggered surveys. NPS scores propagate archetype + recent outage / complaint exposure. ~5% of NPS responses include LLM-generated open-ended comment. NPS responses cover current occupants only (prior-occupant customers excluded). PK: response_id. FK: survey_id -> qualtrics_survey; customer_id -> raw_customer.'
AS

WITH

-- ────────────────────────────────────────────────────────────────────────
-- NPS responses. Cross-join surveys × customers, then filter by sample +
-- response probability. Each quarterly NPS targets ~25% of customers and
-- ~30% respond.
-- ────────────────────────────────────────────────────────────────────────
nps_candidates AS (
  SELECT
    s.survey_id,
    s.launch_date,
    s.close_date,
    c.customer_id,
    c.archetype,
    abs(xxhash64(s.survey_id, c.customer_id, 'sample', ${random_seed}))
      / CAST(9223372036854775807 AS DOUBLE)                          AS r_sample,
    abs(xxhash64(s.survey_id, c.customer_id, 'respond', ${random_seed}))
      / CAST(9223372036854775807 AS DOUBLE)                          AS r_respond,
    abs(xxhash64(s.survey_id, c.customer_id, 'day', ${random_seed}))
      / CAST(9223372036854775807 AS DOUBLE)                          AS r_day,
    abs(xxhash64(s.survey_id, c.customer_id, 'score_jitter', ${random_seed}))
      / CAST(9223372036854775807 AS DOUBLE)                          AS r_jitter,
    abs(xxhash64(s.survey_id, c.customer_id, 'comment', ${random_seed}))
      / CAST(9223372036854775807 AS DOUBLE)                          AS r_comment
  FROM raw_qualtrics_survey s
  CROSS JOIN ${customer_master_schema}.raw_customer c
  WHERE s.survey_type = 'nps_relationship'
    AND NOT c.is_prior_occupant                                        -- current occupants only (no prior-occupant leakage into the current window)
),

nps_responding AS (
  SELECT *,
    -- 25% sampled, 30% of sampled respond -> 7.5% response rate per quarter.
    -- That's ~3,800 responses/quarter × 8 quarters ≈ 30K NPS responses.
    DATE_ADD(launch_date, CAST(r_day * 75 AS INT)) AS response_date
  FROM nps_candidates
  WHERE r_sample < 0.25 AND r_respond < 0.30
),

-- Look up recent outage and complaint exposure to bias the NPS score.
nps_with_exposure AS (
  SELECT
    n.*,
    COALESCE(o.outage_minutes_prior_90d, 0)   AS outage_minutes_prior_90d,
    COALESCE(o.outage_events_prior_90d, 0)    AS outage_events_prior_90d,
    COALESCE(cp.complaint_count_prior_90d, 0) AS complaint_count_prior_90d
  FROM nps_responding n
  LEFT JOIN (
    SELECT
      ci.customer_id,
      n2.survey_id,
      SUM(ci.minutes_out)  AS outage_minutes_prior_90d,
      COUNT(DISTINCT ci.outage_id) AS outage_events_prior_90d
    FROM ${outages_schema}.raw_outage_customer_impact ci
    JOIN nps_responding n2
      ON ci.customer_id = n2.customer_id
     AND ci.affected_start BETWEEN n2.response_date - INTERVAL 90 DAYS
                               AND n2.response_date
    GROUP BY ci.customer_id, n2.survey_id
  ) o ON o.customer_id = n.customer_id AND o.survey_id = n.survey_id
  LEFT JOIN (
    SELECT
      e.customer_id,
      n3.survey_id,
      COUNT(*) AS complaint_count_prior_90d
    FROM ${complaints_schema}.raw_customer_complaint_event e
    JOIN nps_responding n3
      ON e.customer_id = n3.customer_id
     AND e.complaint_date BETWEEN n3.response_date - INTERVAL 90 DAYS
                              AND n3.response_date
    GROUP BY e.customer_id, n3.survey_id
  ) cp ON cp.customer_id = n.customer_id AND cp.survey_id = n.survey_id
),

nps_with_score AS (
  SELECT *,
    -- Archetype base NPS (mean score on 0-10 scale).
    CASE archetype
      WHEN 'efficient_engaged'        THEN 8.5
      WHEN 'tech_forward'             THEN 7.8
      WHEN 'comfortable_indifferent'  THEN 7.0
      WHEN 'senior_fixed_income'      THEN 7.2
      WHEN 'inefficient_unaware'      THEN 5.8
      WHEN 'cost_stressed'            THEN 4.5
      ELSE                                 7.0
    END
    -- Outage penalty (~ -1.5 for heavy outage exposure)
    - LEAST(outage_minutes_prior_90d / 600.0, 3.0)
    -- Complaint penalty (~ -1 per recent complaint, capped at -3)
    - LEAST(complaint_count_prior_90d * 1.0, 3.0)
    -- Per-response jitter +/-1.5
    + (r_jitter - 0.5) * 3.0                                         AS raw_score
  FROM nps_with_exposure
)

SELECT
  md5(CONCAT(survey_id, '_', customer_id))                           AS response_id,
  survey_id,
  customer_id,
  response_date,
  -- Clip to 0-10 and cast to INT.
  CAST(GREATEST(0, LEAST(10, ROUND(raw_score, 0))) AS INT)           AS score,
  -- NPS bucket
  CASE
    WHEN GREATEST(0, LEAST(10, ROUND(raw_score, 0))) >= 9 THEN 'promoter'
    WHEN GREATEST(0, LEAST(10, ROUND(raw_score, 0))) >= 7 THEN 'passive'
    ELSE                                                       'detractor'
  END                                                                AS nps_bucket,

  outage_minutes_prior_90d,
  outage_events_prior_90d,
  complaint_count_prior_90d,

  -- Open-ended comment: ~5% of responses leave one, skewed to detractor.
  CASE
    WHEN r_comment <
      CASE
        WHEN GREATEST(0, LEAST(10, ROUND(raw_score, 0))) <= 6 THEN 0.12  -- detractors talk
        WHEN GREATEST(0, LEAST(10, ROUND(raw_score, 0))) <= 8 THEN 0.05  -- passives sometimes
        ELSE                                                       0.02  -- promoters rarely
      END
    THEN ai_query(
      '${llm_endpoint}',
      CONCAT(
        'Simulate a one-sentence (15-30 word) customer comment on an annual ',
        'utility NPS survey. NPS score: ',
        CAST(GREATEST(0, LEAST(10, ROUND(raw_score, 0))) AS STRING), '/10. ',
        CASE
          WHEN outage_minutes_prior_90d > 240 THEN CONCAT('Recent outage exposure: ', CAST(outage_minutes_prior_90d AS STRING), ' minutes. ')
          ELSE ''
        END,
        CASE
          WHEN complaint_count_prior_90d > 0 THEN CONCAT('Recent complaints: ', CAST(complaint_count_prior_90d AS STRING), '. ')
          ELSE ''
        END,
        'Customer tone: ',
        CASE archetype
          WHEN 'cost_stressed'            THEN 'frustrated, financial concern'
          WHEN 'inefficient_unaware'      THEN 'confused, defensive'
          WHEN 'efficient_engaged'        THEN 'specific, constructive'
          WHEN 'tech_forward'             THEN 'analytical'
          WHEN 'senior_fixed_income'      THEN 'patient, worried'
          ELSE                                 'neutral'
        END,
        '. Output ONLY the comment, no preamble, no quotes.'
      )
    )
    ELSE CAST(NULL AS STRING)
  END                                                                AS comment_text,

  'nps_relationship'                                                 AS survey_type,
  current_timestamp()                                                AS _ingested_at

FROM nps_with_score

UNION ALL

-- ────────────────────────────────────────────────────────────────────────
-- CSAT responses. Sample 10% of Genesys interactions; customer fills out
-- a 1-5 CSAT score post-call (mapped to 0-10 scale for unified table).
-- ────────────────────────────────────────────────────────────────────────
SELECT
  md5(CONCAT('SVY-CSAT-CONT_', i.interaction_id))                   AS response_id,
  'SVY-CSAT-CONT'                                                    AS survey_id,
  i.customer_id,
  CAST(DATE_ADD(CAST(i.started_at AS DATE), 1) AS DATE)              AS response_date,
  -- Map CSAT 1-5 to NPS 0-10 scale (5 -> 10, 4 -> 8, 3 -> 6, 2 -> 4, 1 -> 2)
  CAST(i.csat_score_1_5 * 2 AS INT)                                  AS score,
  CASE
    WHEN i.csat_score_1_5 = 5 THEN 'promoter'
    WHEN i.csat_score_1_5 = 4 THEN 'passive'
    ELSE                          'detractor'
  END                                                                AS nps_bucket,
  CAST(NULL AS INT)                                                  AS outage_minutes_prior_90d,
  CAST(NULL AS INT)                                                  AS outage_events_prior_90d,
  CAST(NULL AS INT)                                                  AS complaint_count_prior_90d,
  CAST(NULL AS STRING)                                               AS comment_text,
  'csat_transactional'                                               AS survey_type,
  current_timestamp()                                                AS _ingested_at
FROM ${genesys_schema}.raw_interaction i
WHERE NOT i.abandoned_flag
  -- 10% sample
  AND abs(xxhash64(i.interaction_id, 'csat_sample', ${random_seed})) % 100 < 10;
