-- Outage Event — CIM Outage-aligned. One row per OMS incident with start
-- time, duration, cause code, weather context, and affected customer count.
-- ~14K events across 2017+2018, calibrated to a major Michigan utility's published reliability:
--   SAIDI ~280 min, SAIFI ~1.5, CAIDI ~190 min.
--
-- Outages are generated by EXPLODE'ing a sequence of synthetic outage_seq
-- values per year, then deriving all attributes deterministically from
-- (outage_seq, year, random_seed) hashes. Each outage is assigned to a
-- synthetic circuit_id (~1,000 circuits across the territory; customers
-- get the same circuit_id derivation in raw_outage_customer_impact.sql).
--
-- Duration distribution (calibrated to CAIDI ~190 min):
--   p50  90 min (typical equipment fault, restored by line crew)
--   p90  300 min (5 hours; bigger equipment or weather-driven)
--   p99  2880 min (48 hours; major-event-day candidate)
-- Implemented as a piecewise inverse-CDF from a uniform random.
--
-- Cause distribution (per the utility's OMS reporting):
--   equipment_failure  40%
--   vegetation         25%
--   weather            18%
--   animal              7%
--   vehicle             5%
--   planned_maintenance 3%
--   unknown             2%
--
-- Major Event Day: IEEE 1366 defines a MED as a day where SAIDI exceeds
-- the daily average + 2.5*stdev. We approximate by flagging outages with
-- affected_customer_count > 5000 OR duration > 24 hours as MED-class.

CREATE OR REFRESH MATERIALIZED VIEW raw_outage_event (
  CONSTRAINT non_null_outage_id     EXPECT (outage_id IS NOT NULL),
  CONSTRAINT non_null_started_at    EXPECT (started_at IS NOT NULL),
  CONSTRAINT positive_duration      EXPECT (duration_minutes > 0),
  CONSTRAINT positive_affected      EXPECT (affected_customer_count > 0),
  CONSTRAINT valid_cause            EXPECT (cause_code IN (
    'equipment_failure','vegetation','weather','animal',
    'vehicle','planned_maintenance','unknown'
  ))
)
COMMENT 'Outage Event — CIM Outage. One row per OMS incident in 2017+2018, calibrated to a major Michigan utility''s published reliability metrics. PK: outage_id. circuit_id is a synthetic key shared with raw_outage_customer_impact for fan-out.'
AS

WITH

years AS (
  SELECT DISTINCT YEAR(d) AS year
  FROM (SELECT EXPLODE(SEQUENCE(
    DATE_ADD(ADD_MONTHS(DATE'${as_of_date}', -CAST('${history_months}' AS INT)), 1),
    DATE'${as_of_date}',
    INTERVAL 1 MONTH
  )) AS d)
),

seqs AS (
  SELECT outage_seq, y.year
  FROM (SELECT EXPLODE(SEQUENCE(1, CAST(${outages_per_year} AS INT))) AS outage_seq) s
  CROSS JOIN years y
),

-- Distinct circuit_ids that exist in the territory. We materialize the
-- circuit list here from customer_master so outage circuit assignment
-- can target a real circuit (not invent one with no customers).
circuits AS (
  SELECT
    abs(xxhash64(census_tract, county_fips)) % 1000 AS circuit_id,
    COUNT(*)                                         AS circuit_customer_count
  FROM ${customer_master_schema}.raw_premises
  GROUP BY abs(xxhash64(census_tract, county_fips)) % 1000
),

circuit_pool AS (
  SELECT
    *,
    ROW_NUMBER() OVER (ORDER BY circuit_id) AS circuit_rank,
    COUNT(*) OVER ()                         AS total_circuits
  FROM circuits
),

raw_outages AS (
  SELECT
    s.outage_seq,
    s.year,
    abs(xxhash64(s.outage_seq, s.year, 'circuit', ${random_seed})) / CAST(9223372036854775807 AS DOUBLE) AS r_circuit,
    abs(xxhash64(s.outage_seq, s.year, 'start',   ${random_seed})) / CAST(9223372036854775807 AS DOUBLE) AS r_start,
    abs(xxhash64(s.outage_seq, s.year, 'dur',     ${random_seed})) / CAST(9223372036854775807 AS DOUBLE) AS r_dur,
    abs(xxhash64(s.outage_seq, s.year, 'cause',   ${random_seed})) / CAST(9223372036854775807 AS DOUBLE) AS r_cause,
    abs(xxhash64(s.outage_seq, s.year, 'affect',  ${random_seed})) / CAST(9223372036854775807 AS DOUBLE) AS r_affect
  FROM seqs s
),

with_circuit AS (
  SELECT
    ro.*,
    cp.circuit_id,
    cp.circuit_customer_count
  FROM raw_outages ro
  JOIN circuit_pool cp
    -- Weighted by circuit_rank so larger circuits attract more outages.
    -- We map r_circuit [0,1) to a circuit_rank in [1, total_circuits].
    ON cp.circuit_rank = LEAST(CAST(ro.r_circuit * cp.total_circuits + 1 AS INT), cp.total_circuits)
),

with_attrs AS (
  SELECT
    *,
    -- Start: uniform across the year (in seconds). Add to Jan 1 of that year.
    TIMESTAMPADD(SECOND,
      CAST(r_start * 365 * 24 * 3600 AS BIGINT),
      MAKE_TIMESTAMP(year, 1, 1, 0, 0, 0, 'UTC')
    )                                                                AS started_at,

    -- Duration: piecewise inverse-CDF for a lognormal-ish distribution.
    -- 60% short (15-90 min), 30% medium (90-300 min), 9% long (300-1440 min),
    -- 1% major event (1440-4320 min = 1-3 days).
    CAST(
      CASE
        WHEN r_dur < 0.60 THEN 15  + r_dur / 0.60 * 75
        WHEN r_dur < 0.90 THEN 90  + (r_dur - 0.60) / 0.30 * 210
        WHEN r_dur < 0.99 THEN 300 + (r_dur - 0.90) / 0.09 * 1140
        ELSE                  1440 + (r_dur - 0.99) / 0.01 * 2880
      END
      AS INT)                                                        AS duration_minutes,

    -- Cause: probabilistic.
    CASE
      WHEN r_cause < 0.40 THEN 'equipment_failure'
      WHEN r_cause < 0.65 THEN 'vegetation'
      WHEN r_cause < 0.83 THEN 'weather'
      WHEN r_cause < 0.90 THEN 'animal'
      WHEN r_cause < 0.95 THEN 'vehicle'
      WHEN r_cause < 0.98 THEN 'planned_maintenance'
      ELSE                     'unknown'
    END                                                              AS cause_code,

    -- Affected customer count. Target ~11 customers/outage average so
    -- 7000 outages/yr x 11 = 77K customer-events/yr / ~50K customers = SAIFI ~1.5.
    -- Realistic distributions are heavy-tailed: most outages affect just
    -- a handful (single tap), some affect circuit-portion (10-100), rare
    -- ones whole circuits (100-400).
    --
    -- Piecewise: 70% small (1-8), 22% medium (8-50), 7% large (50-200),
    -- 1% major (200-600). Clamped to circuit_customer_count. The
    -- aggressive clamping (avg circuit = 66) means major-tier outages
    -- effectively saturate to the full circuit's customer base.
    LEAST(
      circuit_customer_count,
      CAST(
        CASE
          WHEN r_affect < 0.70 THEN 1   + r_affect / 0.70 * 7
          WHEN r_affect < 0.92 THEN 8   + (r_affect - 0.70) / 0.22 * 42
          WHEN r_affect < 0.99 THEN 50  + (r_affect - 0.92) / 0.07 * 150
          ELSE                     200 + (r_affect - 0.99) / 0.01 * 400
        END
        AS INT
      )
    )                                                                AS affected_customer_count
  FROM with_circuit
)

SELECT
  md5(CONCAT('outage_', CAST(year AS STRING), '_', CAST(outage_seq AS STRING))) AS outage_id,
  CAST(circuit_id AS INT)                                            AS circuit_id,
  started_at,
  TIMESTAMPADD(MINUTE, duration_minutes, started_at)                 AS ended_at,
  duration_minutes,
  cause_code,

  -- Weather category — heuristic from cause + season + duration.
  CASE
    WHEN cause_code = 'weather' AND MONTH(started_at) BETWEEN 12 AND 12       THEN 'ice_storm'
    WHEN cause_code = 'weather' AND MONTH(started_at) BETWEEN 1 AND 3         THEN 'ice_storm'
    WHEN cause_code = 'weather' AND MONTH(started_at) BETWEEN 6 AND 8         THEN 'severe_weather'
    WHEN cause_code = 'weather'                                                THEN 'wind_storm'
    WHEN MONTH(started_at) BETWEEN 7 AND 8 AND duration_minutes > 600          THEN 'heat_wave'
    ELSE                                                                            'clear'
  END                                                                AS weather_category,

  affected_customer_count,

  -- Major Event Day flag (approximated by single-outage magnitude rather
  -- than the full IEEE 1366 daily threshold).
  CASE
    WHEN affected_customer_count > 5000 OR duration_minutes > 1440 THEN true
    ELSE                                                                false
  END                                                                AS is_major_event_day,

  current_timestamp()                                                AS _ingested_at
FROM with_attrs;
