-- Social Mention — public social media posts from utility customers.
-- Drivers:
--   (a) Unresolved complaints (status='unpaid' or 'escalated') -> ~3% post publicly
--   (b) Major outages (>= 4 hours single outage) -> ~5% of affected customers post
--   (c) Random baseline -> ~0.1% of customers per year post unprompted
--
-- ~2.5-4K total mentions. LLM-generated text via Llama 3.1 8B.
-- Platform mix: Twitter 45% / Facebook 30% / Google Reviews 15% / Yelp 10%.

CREATE OR REFRESH MATERIALIZED VIEW raw_social_mention (
  CONSTRAINT non_null_mention_id   EXPECT (mention_id IS NOT NULL),
  CONSTRAINT non_null_customer_id  EXPECT (customer_id IS NOT NULL),
  CONSTRAINT valid_platform        EXPECT (platform IN ('twitter','facebook','google_review','yelp')),
  CONSTRAINT valid_sentiment       EXPECT (sentiment_label IN ('negative','very_negative','mixed','positive'))
)
COMMENT 'Social Mention — public social posts from utility customers. LLM-generated by Llama 3.1 8B. Driven from unresolved complaints + major outages + random baseline. ~3K rows. PK: mention_id. FK: customer_id -> raw_customer (in reality this link comes via fuzzy social-handle matching, modeled in social_match).'
AS

WITH

-- (a) Unresolved complaints — ~3% of escalated / unpaid complaints become public posts.
from_complaints AS (
  SELECT
    e.customer_id,
    e.complaint_id                              AS source_complaint_id,
    CAST(NULL AS STRING)                        AS source_outage_id,
    e.category,
    e.sub_category,
    e.bill_shock_pct,
    e.outage_minutes_30d,
    e.complaint_date                            AS posted_around,
    'complaint_unresolved'                      AS post_driver,
    abs(xxhash64(e.complaint_id, 'soc_post', ${random_seed}))
      / CAST(9223372036854775807 AS DOUBLE)     AS r_post,
    abs(xxhash64(e.complaint_id, 'soc_platform', ${random_seed}))
      / CAST(9223372036854775807 AS DOUBLE)     AS r_platform,
    abs(xxhash64(e.complaint_id, 'soc_day', ${random_seed}))
      / CAST(9223372036854775807 AS DOUBLE)     AS r_day,
    abs(xxhash64(e.complaint_id, 'soc_engage', ${random_seed}))
      / CAST(9223372036854775807 AS DOUBLE)     AS r_engage,
    abs(xxhash64(e.complaint_id, 'soc_reach', ${random_seed}))
      / CAST(9223372036854775807 AS DOUBLE)     AS r_reach
  FROM ${complaints_schema}.raw_customer_complaint_event e
  WHERE e.resolution_status IN ('escalated', 'open')
),
from_complaints_sampled AS (
  SELECT * FROM from_complaints WHERE r_post < 0.10  -- ~10% of escalated/open
),

-- (b) Major outages — ~5% of customers in 4-hour+ outages post publicly.
from_outages AS (
  SELECT
    oci.customer_id,
    CAST(NULL AS STRING)                        AS source_complaint_id,
    o.outage_id                                 AS source_outage_id,
    'outage'                                    AS category,
    CASE
      WHEN o.duration_minutes > 720 THEN 'extended_outage'
      ELSE                               'restoration_delay'
    END                                         AS sub_category,
    0.0                                         AS bill_shock_pct,
    o.duration_minutes                          AS outage_minutes_30d,
    o.started_at                                AS posted_around,
    'major_outage'                              AS post_driver,
    abs(xxhash64(oci.impact_id, 'soc_post', ${random_seed}))
      / CAST(9223372036854775807 AS DOUBLE)     AS r_post,
    abs(xxhash64(oci.impact_id, 'soc_platform', ${random_seed}))
      / CAST(9223372036854775807 AS DOUBLE)     AS r_platform,
    abs(xxhash64(oci.impact_id, 'soc_day', ${random_seed}))
      / CAST(9223372036854775807 AS DOUBLE)     AS r_day,
    abs(xxhash64(oci.impact_id, 'soc_engage', ${random_seed}))
      / CAST(9223372036854775807 AS DOUBLE)     AS r_engage,
    abs(xxhash64(oci.impact_id, 'soc_reach', ${random_seed}))
      / CAST(9223372036854775807 AS DOUBLE)     AS r_reach
  FROM ${outages_schema}.raw_outage_customer_impact oci
  JOIN ${outages_schema}.raw_outage_event o USING (outage_id)
  WHERE o.duration_minutes >= 240   -- 4+ hour outage
),
from_outages_sampled AS (
  SELECT * FROM from_outages WHERE r_post < 0.05
),

-- (c) Random baseline — ~0.1% of customers post unprompted per year.
from_baseline AS (
  SELECT
    c.customer_id,
    CAST(NULL AS STRING)                                              AS source_complaint_id,
    CAST(NULL AS STRING)                                              AS source_outage_id,
    'customer_service'                                                AS category,
    'general_feedback'                                                AS sub_category,
    0.0                                                               AS bill_shock_pct,
    0                                                                 AS outage_minutes_30d,
    -- Pick a random date in 2017+2018 for posting.
    TIMESTAMPADD(DAY,
      CAST(abs(xxhash64(c.customer_id, y.year, 'soc_day_pick', ${random_seed})) % 365 AS INT),
      MAKE_TIMESTAMP(y.year, 1, 1, 12, 0, 0, 'UTC'))                  AS posted_around,
    'baseline_unprompted'                                             AS post_driver,
    abs(xxhash64(c.customer_id, y.year, 'soc_post', ${random_seed}))
      / CAST(9223372036854775807 AS DOUBLE)                           AS r_post,
    abs(xxhash64(c.customer_id, y.year, 'soc_platform', ${random_seed}))
      / CAST(9223372036854775807 AS DOUBLE)                           AS r_platform,
    abs(xxhash64(c.customer_id, y.year, 'soc_dayhash', ${random_seed}))
      / CAST(9223372036854775807 AS DOUBLE)                           AS r_day,
    abs(xxhash64(c.customer_id, y.year, 'soc_engage', ${random_seed}))
      / CAST(9223372036854775807 AS DOUBLE)                           AS r_engage,
    abs(xxhash64(c.customer_id, y.year, 'soc_reach', ${random_seed}))
      / CAST(9223372036854775807 AS DOUBLE)                           AS r_reach
  FROM ${customer_master_schema}.raw_customer c
  CROSS JOIN (SELECT 2017 AS year UNION ALL SELECT 2018) y
  WHERE NOT c.is_prior_occupant                                          -- current occupants only (no prior-occupant baseline posts in the 2017-2018 window)
    AND abs(xxhash64(c.customer_id, y.year, 'baseline_pick', ${random_seed})) % 1000 < 1
),

unioned AS (
  SELECT * FROM from_complaints_sampled
  UNION ALL
  SELECT * FROM from_outages_sampled
  UNION ALL
  SELECT * FROM from_baseline
),

with_attrs AS (
  SELECT
    u.*,
    -- Platform mix.
    CASE
      WHEN u.r_platform < 0.45 THEN 'twitter'
      WHEN u.r_platform < 0.75 THEN 'facebook'
      WHEN u.r_platform < 0.90 THEN 'google_review'
      ELSE                          'yelp'
    END                                                              AS platform,
    c.archetype,
    c.language_preference
  FROM unioned u
  JOIN ${customer_master_schema}.raw_customer c USING (customer_id)
)

SELECT
  md5(CONCAT(customer_id, '_',
             COALESCE(source_complaint_id, ''),
             COALESCE(source_outage_id, ''),
             post_driver,
             CAST(posted_around AS STRING)))                         AS mention_id,
  customer_id,
  platform,

  -- Posted timestamp: 0-7 days after the trigger (complaint / outage).
  TIMESTAMPADD(HOUR, CAST(r_day * 168 AS INT), posted_around)        AS posted_at,

  source_complaint_id,
  source_outage_id,
  post_driver,
  category,
  sub_category,

  -- Sentiment.
  CASE
    WHEN post_driver = 'complaint_unresolved' AND bill_shock_pct > 0.30 THEN 'very_negative'
    WHEN post_driver = 'major_outage' AND outage_minutes_30d > 720    THEN 'very_negative'
    WHEN post_driver IN ('complaint_unresolved','major_outage')         THEN 'negative'
    WHEN post_driver = 'baseline_unprompted' AND archetype = 'tech_forward' AND r_engage < 0.40 THEN 'positive'
    WHEN post_driver = 'baseline_unprompted' AND archetype = 'efficient_engaged' AND r_engage < 0.35 THEN 'positive'
    WHEN post_driver = 'baseline_unprompted'                            THEN 'mixed'
    ELSE                                                                     'negative'
  END                                                                AS sentiment_label,

  -- Reach (followers / friends).
  CAST(
    CASE
      WHEN r_reach < 0.65 THEN 50  + r_reach / 0.65 * 250    -- typical 50-300
      WHEN r_reach < 0.92 THEN 300 + (r_reach - 0.65) / 0.27 * 1700  -- 300-2000
      WHEN r_reach < 0.99 THEN 2000 + (r_reach - 0.92) / 0.07 * 8000  -- 2K-10K
      ELSE                       10000 + (r_reach - 0.99) / 0.01 * 90000  -- viral 10K-100K
    END
    AS INT)                                                          AS reach_estimate,

  -- Engagement (likes + shares + replies)
  CAST(r_engage * 50 AS INT)                                         AS engagement_count,

  -- LLM-generated post text. Tighter prompt than complaints because
  -- platforms have character limits (Twitter ~280, others longer).
  ai_query('${llm_endpoint}',
    CONCAT(
      'Simulate a brief public ', platform,
      CASE WHEN platform IN ('google_review','yelp') THEN ' review' ELSE ' post' END,
      ' from a utility customer. ',
      CASE WHEN platform = 'twitter' THEN '160-280 characters max, can include @theutility and a hashtag. ' ELSE '40-80 words. ' END,
      'Tone: ',
      CASE
        WHEN bill_shock_pct > 0.30 THEN 'angry, financial frustration'
        WHEN outage_minutes_30d > 720 THEN 'angry, safety concerns'
        WHEN outage_minutes_30d > 240 THEN 'frustrated, demanding answers'
        WHEN post_driver = 'baseline_unprompted' AND archetype IN ('tech_forward','efficient_engaged') THEN 'measured, possibly constructive feedback or rare praise'
        ELSE 'frustrated'
      END, '. ',
      CASE WHEN outage_minutes_30d > 0
           THEN CONCAT('Context: ', CAST(outage_minutes_30d AS STRING), ' minutes without power recently. ')
           ELSE ''
      END,
      CASE WHEN bill_shock_pct > 0.15
           THEN CONCAT('Bill is ', CAST(CAST(bill_shock_pct * 100 AS INT) AS STRING), '% higher than usual. ')
           ELSE ''
      END,
      'Output ONLY the post text, no preamble, no quotes.'
    )
  )                                                                  AS mention_text,

  current_timestamp()                                                AS _ingested_at

FROM with_attrs;
