-- Customer Complaint Text — verbatim complaint narratives generated by
-- ai_query against the Foundation Model API. One row per complaint event.
--
-- Uses databricks-meta-llama-3-1-8b-instruct (the cheapest first-party
-- served model). At ~$0.000026/call x 15-20K events ≈ $0.50 total to
-- populate. ~5% of events with language_preference='ES' get Spanish
-- output (lights up the ai_translate demo beat).
--
-- The prompt embeds the deterministic structured fields from
-- customer_complaint_event so the LLM's job is purely surface-level
-- (the substance of the complaint is already decided by the propensity
-- model upstream). Output target: 30-50 words, 1-2 sentences, first
-- person, customer's tone matched to archetype.
--
-- The two tables are kept separate so the structured event fields can
-- be refreshed without re-calling the LLM. SDP will rerun ai_query on
-- every refresh of THIS MV; that costs ~$0.50 per refresh.

CREATE OR REFRESH MATERIALIZED VIEW raw_customer_complaint_text (
  CONSTRAINT non_null_complaint_id EXPECT (complaint_id IS NOT NULL),
  CONSTRAINT non_null_verbatim     EXPECT (verbatim_text IS NOT NULL),
  CONSTRAINT valid_language        EXPECT (language IN ('en','es'))
)
COMMENT 'Customer Complaint Text — LLM-generated verbatim complaint narratives. One row per complaint_event. Generated via ai_query against databricks-meta-llama-3-1-8b-instruct with structured prompt embedding category, sub_category, bill shock, outage exposure, channel, and archetype tone. ~5% of ES-preference customers get Spanish output. PK: complaint_id (1:1 with customer_complaint_event).'
AS

WITH

prompt_input AS (
  SELECT
    e.complaint_id,
    e.customer_id,
    e.category,
    e.sub_category,
    e.severity,
    e.sentiment_label,
    e.channel,
    e.triggering_bill_amount,
    e.trailing_12_avg_bill,
    e.bill_shock_pct,
    e.outage_minutes_30d,
    e.outages_count_30d,
    c.archetype,
    c.language_preference,
    abs(xxhash64(e.complaint_id, 'lang_draw'))
      / CAST(9223372036854775807 AS DOUBLE)                          AS r_lang
  FROM raw_customer_complaint_event e
  JOIN ${customer_master_schema}.raw_customer c USING (customer_id)
),

with_language AS (
  SELECT
    *,
    -- ES for ~5% of complaints from ES-preference customers.
    CASE WHEN language_preference = 'ES' AND r_lang < 0.50 THEN 'es' ELSE 'en' END
      AS language
  FROM prompt_input
),

with_prompt AS (
  SELECT
    *,
    -- Archetype tone hint for the LLM.
    CASE archetype
      WHEN 'efficient_engaged'        THEN 'measured, well-informed, expects clear answers'
      WHEN 'tech_forward'             THEN 'analytical, demanding, references specifics'
      WHEN 'comfortable_indifferent'  THEN 'matter-of-fact, neutral'
      WHEN 'inefficient_unaware'      THEN 'confused, defensive'
      WHEN 'senior_fixed_income'      THEN 'patient but worried, deferential'
      WHEN 'cost_stressed'            THEN 'anxious, frustrated, financial strain evident'
      ELSE                                 'neutral'
    END                                                              AS tone,

    -- Prompt body. Built with concat so the LLM gets a tight, factual
    -- context and clear instruction.
    CONCAT(
      'Simulate a brief utility-customer complaint in first person. ',
      CASE WHEN language = 'es' THEN 'Respond in Spanish (Latin American). ' ELSE '' END,
      'Output 30-50 words, 1-2 sentences. No preamble, no quotes, no signoff. ',
      'Customer is calling the utility via ', channel, '. ',
      'Category: ', category, ' (', sub_category, '). ',
      'Severity: ', severity, '. Sentiment: ', sentiment_label, '. ',
      CASE
        WHEN bill_shock_pct > 0.15
          THEN CONCAT('This month bill $', ROUND(triggering_bill_amount, 0),
                      ' vs typical $', ROUND(trailing_12_avg_bill, 0), ' (',
                      CAST(ROUND(bill_shock_pct * 100, 0) AS STRING), '% higher). ')
        ELSE ''
      END,
      CASE
        WHEN outage_minutes_30d > 60
          THEN CONCAT('Recent outages: ', CAST(outages_count_30d AS STRING),
                      ' in last 30 days totaling ', CAST(outage_minutes_30d AS STRING), ' minutes. ')
        ELSE ''
      END,
      'Tone: ', tone, '. ',
      'Output ONLY the complaint statement.'
    )                                                                AS prompt
  FROM with_language
)

SELECT
  complaint_id,
  language,
  -- Call the Foundation Model. SDP runs this in parallel across partitions.
  ai_query('${llm_endpoint}', prompt)                                AS verbatim_text,
  '${llm_endpoint}'                                                  AS llm_endpoint,
  current_timestamp()                                                AS _ingested_at
FROM with_prompt;
